## Numpy

수치해석, 수학적 처리, 통계 등을 위한 모듈 - Pandas, Matplotlib, Scipy

### Numpy
```python
!pip install numpy
```

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Source\iot-bigdata-2023\da_env\Lib\site-packages
Requires: 
Required-by: pandas


In [3]:
!pip install matplotlib

     ---------------------------------------- 0.0/7.5 MB ? eta -:--:--
     --- ------------------------------------ 0.6/7.5 MB 13.1 MB/s eta 0:00:01
     ------- -------------------------------- 1.3/7.5 MB 13.9 MB/s eta 0:00:01
     ------------ --------------------------- 2.3/7.5 MB 16.5 MB/s eta 0:00:01
     ------------------- -------------------- 3.6/7.5 MB 19.0 MB/s eta 0:00:01
     --------------------------- ------------ 5.2/7.5 MB 21.9 MB/s eta 0:00:01
     -------------------------------------- - 7.2/7.5 MB 25.7 MB/s eta 0:00:01
     ---------------------------------------  7.5/7.5 MB 26.6 MB/s eta 0:00:01
     ---------------------------------------  7.5/7.5 MB 26.6 MB/s eta 0:00:01
     ---------------------------------------- 7.5/7.5 MB 18.5 MB/s eta 0:00:00
     ---------------------------------------- 0.0/470.9 kB ? eta -:--:--
     ------------------------------------- 470.9/470.9 kB 14.9 MB/s eta 0:00:00
     ---------------------------------------- 0.0/2.1 MB ? eta -:


[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd
import numpy as np

##### Numpy 사용 이유
- python에서 리스트를 1,000,000건 만들고 사용 처리시 대략 200ms가 소요
- numpy에서 배열을 1,000,000건 만들고 사용처리시 대략 20ms가 소요

In [5]:
py_list = list(range(1_000_000))    # 100만건 리스트
np_arr = np.arange(1_000_000)       # 100만건 리스트

In [8]:
%timeit for _ in range(10): py_list2 = py_list * 3

200 ms ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit for _ in range(10): np_arr2 = np_arr * 3

15 ms ± 566 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Numpy로 배열 생성, 연산

- 파이썬 리스트 +, * 연산밖에 없음
- 행렬(벡터) 연산이 필요하면 Numpy로 형변환 후 처리가능

In [15]:
list1 = np.array([[1, 2, 3], [4, 5, 6]])

#### Numpy 연산

In [11]:
list2 = [4, 5, 6]
np_arr1 = np.array(list2)

In [12]:
np_arr1

array([4, 5, 6])

In [13]:
np_arr2 = np.array([[1, 2, 3], [4, 5, 6]])
np_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np_arr3 = np.array(list1)
np_arr4 = np.array(list2)

In [20]:
np_arr3 + np_arr4

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.empty([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.random.randn(50)

array([-1.49498977,  0.99548163, -0.35148155,  0.60559964,  0.06283769,
       -0.50207595, -2.0758975 , -0.22270174,  0.86170814, -1.71417725,
        0.51231594,  1.19705096,  0.80469325, -0.71996221, -0.04108987,
       -0.24432735,  0.24537953, -0.27245024, -0.47636476,  0.43252752,
        0.84175561, -0.10414062,  0.42609705,  1.25157562,  0.44408434,
        0.2604794 , -0.4256604 ,  1.31111898, -0.26838164,  0.75366289,
       -0.76736358,  1.12487368, -1.74525375, -0.17649913,  0.20161145,
       -0.48714335, -0.94895722, -0.31833819, -0.01803172,  1.13967001,
       -1.40330152, -1.98110603,  0.35180414, -0.33618068,  0.31092267,
       -0.60736346,  1.1085542 ,  0.87191645, -0.38781416, -0.24279514])

In [26]:
np.random.randn(5, 4)

array([[-0.64042443, -0.43760717, -0.6246112 ,  0.7070047 ],
       [-0.06455195, -0.9606967 , -1.29533124,  1.13713815],
       [ 0.0740236 ,  1.68942881,  0.19951273, -1.17374583],
       [-0.52841771, -1.55353515, -1.52792611,  1.21377948],
       [ 0.7075541 ,  1.00420231,  0.78754602,  0.46928197]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
(np_arr3 + np_arr4) < 9

array([[ True,  True, False],
       [ True, False, False]])

In [30]:
(np_arr3 + np_arr4) == 9

array([[False, False,  True],
       [False, False, False]])

#### Numpy 속성

In [31]:
# 1차원 배열은 열값이 앞에 나오고
np_arr1.shape

(3,)

In [32]:
# 2차원부터는 행, 열순
np_arr2.shape

(2, 3)

In [33]:
np_arr2.dtype

dtype('int32')

In [34]:
np_arr2.T.shape

(3, 2)

#### 기타 함수

In [35]:
np_arr5 = np.arange(10)
np_arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 평균
np_arr5.mean()

4.5

In [37]:
# 합계
np_arr5.sum()

45

In [38]:
# 적층형 합계
np_arr5.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [39]:
np_arr6 = np.random.randn(10)
np_arr6

array([ 0.12523164,  1.11539169, -0.1288201 , -1.99912747,  0.2654798 ,
        0.78444815,  0.73700085,  0.15469803, -0.44223398, -0.65236884])

In [42]:
np_arr6 = np_arr6 * 10

In [43]:
np_arr6

array([  1.25231641,  11.15391693,  -1.28820097, -19.99127468,
         2.65479798,   7.84448154,   7.37000845,   1.54698035,
        -4.42233983,  -6.52368839])

In [44]:
np_arr6.sort()

In [45]:
np_arr6

array([-19.99127468,  -6.52368839,  -4.42233983,  -1.28820097,
         1.25231641,   1.54698035,   2.65479798,   7.37000845,
         7.84448154,  11.15391693])